DotNetHighcharts/Controllers/DemoController.cs
namespace DotNetHighcharts.Controllers
{
    using System.Web.Mvc;
    using System.Drawing;

    using hc = DotNet.Highcharts;

    public class DemoController : Controller
    {
        // GET: Demo

        #region Public Methods and Operators

        public ActionResult Index()
        {
            var pieChart = new hc.Highcharts("pieChart");
            return View(pieChart);
        }

        #endregion
    }
}

DotNetHighcharts/Controllers/DotNetHighChartsDemoController.cs
using System.Drawing;
using System.Web.Mvc;

namespace DotNetHighcharts.Controllers
{
    using hc = DotNet.Highcharts;

    public class DotNetHighChartsDemoController : Controller
    {
        // GET: DotNetHighChartsDemo
        public ActionResult Index()
        {
            var pieChart = new hc.Highcharts("pieChart");

            pieChart.InitChart(new hc.Options.Chart());
            pieChart.SetTitle(new hc.Options.Title {Text = "Browser market shares, 2014"});
            pieChart.SetSeries(new hc.Options.Series
            {
                Type = hc.Enums.ChartTypes.Pie,
                Data = new hc.Helpers.Data(new[]
                {
                    new hc.Options.Point
                    {
                        Name = "Firefox",
                        Y = 45.0
                    },
                    new hc.Options.Point
                    {
                        Name = "IE",
                        Y = 26.8
                    },
                    new hc.Options.Point
                    {
                        Name = "Chrome",
                        Y = 12.8,
                        Sliced = true,
                        Color = Color.Red
                    },
                    new hc.Options.Point
                    {
                        Name = "Safari",
                        Y = 8.5
                    },
                    new hc.Options.Point
                    {
                        Name = "Opera",
                        Y = 6.2
                    },
                    new hc.Options.Point
                    {
                        Name = "Others",
                        Y = 0.7
                    }
                })
            });

            return View(pieChart);
        }
    }
}

DotNetHighcharts/Views/Demo/Index.cshtml
@model DotNet.Highcharts.Highcharts

@{
    ViewBag.Title = "Pie chart";
}

@Model.ChartScriptHtmlString()
@Model.ChartContainerHtmlString()

DotNetHighcharts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - R&amp;D Academy Hightcharts</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
    @* Highcharts *@
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>
    
    @* Client-side export Highcharts *@
    @*<script src="~/Scripts/Highcharts-4.0.1/js/modules/exporting.js"></script>
    <script src="~/Scripts/Highcharts-4.0.1/js/modules/canvas-tools.js"></script>
    <script src="~/Scripts/jspdf.min.js"></script>
    <script src="~/Scripts/export-csv.js"></script>
    <script src="~/Scripts/highcharts-export-clientside.js"></script>*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("R&D Academy", "Index", "Demo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Talentsoft - Internal confidential</p>
        </footer>
    </div>

    
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>